/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DoctorConsultationRouteImport } from './routes/doctor-consultation'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeDiagnosticsRouteImport } from './routes/home-diagnostics'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as LabTestRouteImport } from './routes/lab-test'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountAuditLogsRouteImport } from './routes/account/audit-logs'
import { Route as AccountMedicinesRouteImport } from './routes/account.medicines'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as BookDoctorIdRouteImport } from './routes/book-doctor.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ConsultationIdRouteImport } from './routes/consultation.$id'
import { Route as MedicineIdRouteImport } from './routes/medicine.$id'
import { Route as PrescriptionIndexRouteImport } from './routes/prescription.index'
import { Route as PrescriptionIdRouteImport } from './routes/prescription.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as RxShareTokenRouteImport } from './routes/rx-share.$token'
import { Route as RxIdRouteImport } from './routes/rx.$id'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as TrackNoRouteImport } from './routes/track.$no'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as SharedProductRouteImport } from './routes/shared/product.'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/doctor-consultation',
  path: '/doctor-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDiagnosticsRoute = HomeDiagnosticsRouteImport.update({
  id: '/home-diagnostics',
  path: '/home-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestRoute = LabTestRouteImport.update({
  id: '/lab-test',
  path: '/lab-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAuditLogsRoute = AccountAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMedicinesRoute = AccountMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book-doctor/$id',
  path: '/book-doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIdRoute = ConsultationIdRouteImport.update({
  id: '/consultation/$id',
  path: '/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineIdRoute = MedicineIdRouteImport.update({
  id: '/medicine/$id',
  path: '/medicine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionIndexRoute = PrescriptionIndexRouteImport.update({
  id: '/prescription/',
  path: '/prescription/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionIdRoute = PrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RxShareTokenRoute = RxShareTokenRouteImport.update({
  id: '/rx-share/$token',
  path: '/rx-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RxIdRoute = RxIdRouteImport.update({
  id: '/rx/$id',
  path: '/rx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackNoRoute = TrackNoRouteImport.update({
  id: '/track/$no',
  path: '/track/$no',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedProductRoute = SharedProductRouteImport.update({
  id: '/shared/product/',
  path: '/shared/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/home-services': typeof HomeServicesRoute
  '/lab-test': typeof LabTestRoute
  '/medicines': typeof MedicinesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/audit-logs': typeof AccountAuditLogsRoute
  '/account/medicines': typeof AccountMedicinesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx-share/$token': typeof RxShareTokenRoute
  '/rx/$id': typeof RxIdRoute
  '/t/$token': typeof TTokenRoute
  '/track/$no': typeof TrackNoRoute
  '/prescription/': typeof PrescriptionIndexRoute
  '/shared/product/': typeof SharedProductRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/home-services': typeof HomeServicesRoute
  '/lab-test': typeof LabTestRoute
  '/medicines': typeof MedicinesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/audit-logs': typeof AccountAuditLogsRoute
  '/account/medicines': typeof AccountMedicinesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx-share/$token': typeof RxShareTokenRoute
  '/rx/$id': typeof RxIdRoute
  '/t/$token': typeof TTokenRoute
  '/track/$no': typeof TrackNoRoute
  '/prescription': typeof PrescriptionIndexRoute
  '/shared/product': typeof SharedProductRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/doctor-consultation': typeof DoctorConsultationRoute
  '/help': typeof HelpRoute
  '/home-diagnostics': typeof HomeDiagnosticsRoute
  '/home-services': typeof HomeServicesRoute
  '/lab-test': typeof LabTestRoute
  '/medicines': typeof MedicinesRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/audit-logs': typeof AccountAuditLogsRoute
  '/account/medicines': typeof AccountMedicinesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/book-doctor/$id': typeof BookDoctorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/consultation/$id': typeof ConsultationIdRoute
  '/medicine/$id': typeof MedicineIdRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rx-share/$token': typeof RxShareTokenRoute
  '/rx/$id': typeof RxIdRoute
  '/t/$token': typeof TTokenRoute
  '/track/$no': typeof TrackNoRoute
  '/prescription/': typeof PrescriptionIndexRoute
  '/shared/product/': typeof SharedProductRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/home-services'
    | '/lab-test'
    | '/medicines'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/wishlist'
    | '/account/audit-logs'
    | '/account/medicines'
    | '/account/notifications'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/medicine/$id'
    | '/prescription/$id'
    | '/product/$id'
    | '/rx-share/$token'
    | '/rx/$id'
    | '/t/$token'
    | '/track/$no'
    | '/prescription/'
    | '/shared/product/'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/home-services'
    | '/lab-test'
    | '/medicines'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/wishlist'
    | '/account/audit-logs'
    | '/account/medicines'
    | '/account/notifications'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/medicine/$id'
    | '/prescription/$id'
    | '/product/$id'
    | '/rx-share/$token'
    | '/rx/$id'
    | '/t/$token'
    | '/track/$no'
    | '/prescription'
    | '/shared/product'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appointments'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/doctor-consultation'
    | '/help'
    | '/home-diagnostics'
    | '/home-services'
    | '/lab-test'
    | '/medicines'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/wishlist'
    | '/account/audit-logs'
    | '/account/medicines'
    | '/account/notifications'
    | '/book-doctor/$id'
    | '/category/$slug'
    | '/consultation/$id'
    | '/medicine/$id'
    | '/prescription/$id'
    | '/product/$id'
    | '/rx-share/$token'
    | '/rx/$id'
    | '/t/$token'
    | '/track/$no'
    | '/prescription/'
    | '/shared/product/'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  HelpRoute: typeof HelpRoute
  HomeDiagnosticsRoute: typeof HomeDiagnosticsRoute
  HomeServicesRoute: typeof HomeServicesRoute
  LabTestRoute: typeof LabTestRoute
  MedicinesRoute: typeof MedicinesRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ConsultationIdRoute: typeof ConsultationIdRoute
  MedicineIdRoute: typeof MedicineIdRoute
  PrescriptionIdRoute: typeof PrescriptionIdRoute
  ProductIdRoute: typeof ProductIdRoute
  RxShareTokenRoute: typeof RxShareTokenRoute
  RxIdRoute: typeof RxIdRoute
  TTokenRoute: typeof TTokenRoute
  TrackNoRoute: typeof TrackNoRoute
  PrescriptionIndexRoute: typeof PrescriptionIndexRoute
  SharedProductRoute: typeof SharedProductRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-consultation': {
      id: '/doctor-consultation'
      path: '/doctor-consultation'
      fullPath: '/doctor-consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-diagnostics': {
      id: '/home-diagnostics'
      path: '/home-diagnostics'
      fullPath: '/home-diagnostics'
      preLoaderRoute: typeof HomeDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-test': {
      id: '/lab-test'
      path: '/lab-test'
      fullPath: '/lab-test'
      preLoaderRoute: typeof LabTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/audit-logs': {
      id: '/account/audit-logs'
      path: '/audit-logs'
      fullPath: '/account/audit-logs'
      preLoaderRoute: typeof AccountAuditLogsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/medicines': {
      id: '/account/medicines'
      path: '/medicines'
      fullPath: '/account/medicines'
      preLoaderRoute: typeof AccountMedicinesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/book-doctor/$id': {
      id: '/book-doctor/$id'
      path: '/book-doctor/$id'
      fullPath: '/book-doctor/$id'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$id': {
      id: '/consultation/$id'
      path: '/consultation/$id'
      fullPath: '/consultation/$id'
      preLoaderRoute: typeof ConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/$id': {
      id: '/medicine/$id'
      path: '/medicine/$id'
      fullPath: '/medicine/$id'
      preLoaderRoute: typeof MedicineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/': {
      id: '/prescription/'
      path: '/prescription'
      fullPath: '/prescription/'
      preLoaderRoute: typeof PrescriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/$id': {
      id: '/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/prescription/$id'
      preLoaderRoute: typeof PrescriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rx-share/$token': {
      id: '/rx-share/$token'
      path: '/rx-share/$token'
      fullPath: '/rx-share/$token'
      preLoaderRoute: typeof RxShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rx/$id': {
      id: '/rx/$id'
      path: '/rx/$id'
      fullPath: '/rx/$id'
      preLoaderRoute: typeof RxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$no': {
      id: '/track/$no'
      path: '/track/$no'
      fullPath: '/track/$no'
      preLoaderRoute: typeof TrackNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/product/': {
      id: '/shared/product/'
      path: '/shared/product'
      fullPath: '/shared/product/'
      preLoaderRoute: typeof SharedProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAuditLogsRoute: typeof AccountAuditLogsRoute
  AccountMedicinesRoute: typeof AccountMedicinesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAuditLogsRoute: AccountAuditLogsRoute,
  AccountMedicinesRoute: AccountMedicinesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  DoctorConsultationRoute: DoctorConsultationRoute,
  HelpRoute: HelpRoute,
  HomeDiagnosticsRoute: HomeDiagnosticsRoute,
  HomeServicesRoute: HomeServicesRoute,
  LabTestRoute: LabTestRoute,
  MedicinesRoute: MedicinesRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ConsultationIdRoute: ConsultationIdRoute,
  MedicineIdRoute: MedicineIdRoute,
  PrescriptionIdRoute: PrescriptionIdRoute,
  ProductIdRoute: ProductIdRoute,
  RxShareTokenRoute: RxShareTokenRoute,
  RxIdRoute: RxIdRoute,
  TTokenRoute: TTokenRoute,
  TrackNoRoute: TrackNoRoute,
  PrescriptionIndexRoute: PrescriptionIndexRoute,
  SharedProductRoute: SharedProductRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
